apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-coffee
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-app-coffee
  template:
    metadata:
      labels:
        app: demo-app-coffee
    spec:
      containers:
        - name: demo-app-coffee
          image: rafayus/demo-app-coffee:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
      terminationGracePeriodSeconds: 0
