apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2020-02-12T21:43:21Z"
  labels:
    run: redis
  name: redis
  namespace: web
  resourceVersion: "19522"
  selfLink: /api/v1/namespaces/web/pods/redis
  uid: b06bcb37-4de0-11ea-9f8c-42010a80018b
spec:
  containers:
  - image: redis
    imagePullPolicy: Always
    name: redis
    ports:
    - containerPort: 9090
      protocol: TCP
    resources:
      limits:
        memory: "1Gi"
        cpu: "200m"
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-c5t8t
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: gke-standard-cluster-1-default-pool-9882e669-4n1v
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-c5t8t
    secret:
      defaultMode: 420
      secretName: default-token-c5t8t
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-02-12T21:43:21Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-02-12T21:43:27Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-02-12T21:43:27Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-02-12T21:43:21Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://c93711e3daa16640ba70f62d510e7e356525e25bd9aba803db172fb69865b97e
    image: redis:latest
    imageID: docker-pullable://redis@sha256:d8fa379d0db05f5a57c0bb6a85457d2fe4254053e35ece01bc53fbcf679bc10a
    lastState: {}
    name: redis
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: "2020-02-12T21:43:27Z"
  hostIP: 10.128.0.4
  phase: Running
  podIP: 10.8.2.4
  qosClass: BestEffort
  startTime: "2020-02-12T21:43:21Z"
