apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: name-virtual-host-ingress
  namespace: tools
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"

spec:
  rules:

  - host: vault.murodbey.com
    http:
      paths:
      - backend:
          serviceName: vault-service
          servicePort: 8083

  - host: nexus.murodbey.com
    http:
      paths:
      - backend:
          serviceName: nexus-service
          servicePort: 8081

  - host: grafana.murodbey.com
    http:
      paths:
      - backend:
          serviceName: grafana-service
          servicePort: 8082