apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jira-pvc
  namespace: tools
  labels:
    app: jira-deployment
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: jira-deployment
  name: jira-deployment
  namespace: tools
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jira-deployment
    spec:
      containers:
        - image: gcr.io/hightowerlabs/jira:7.3.6-standalone
          imagePullPolicy: Always
          name: jira-deployment
          ports:
          - containerPort: 8000
            protocol: TCP
            name: http
          volumeMounts:
            - name: jira-pvc
              mountPath: /var/run
      volumes:
        - name: jira-pvc
          persistentVolumeClaim:
            claimName: jira-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: jira-service
  labels:
    app: jira-deployment
  namespace: tools
spec:
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: jira-deployment
  type: LoadBalancer