apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jira-pvc
  namespace: tools
  labels:
    app: jira-deployment
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: jira-deployment
  name: jira-deployment
  namespace: tools
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jira-deployment
    spec:
      containers:
        - name: jira-deployment
          image: cptactionhank/atlassian-jira
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8090
            protocol: TCP
          volumeMounts:
            - name: jira-pvc
              mountPath: /var/lib/jira
      volumes:
        - name: jira-pvc
          persistentVolumeClaim:
            claimName: jira-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: jira-service
  labels:
    app: jira-deployment
  namespace: tools
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8090

  selector:
    app: jira-deployment
  type: LoadBalancer