apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitbucket-pvc
  namespace: tools
  labels:
    app: bitbucket
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bitbucket-deployment
  namespace: tools
  labels:
    app: bitbucket
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bitbucket
    spec:
      containers:
        - name: bitbucket-container
          image: "atlassian/bitbucket-server:latest"
          resources:
            requests:
              cpu: 500m
              memory: 4800Mi
          ports:
            - containerPort: 7990
              protocol: TCP
              name: http
          volumeMounts:
            - name: bitbucket-volume
              mountPath: /bitbucket-data
      volumes:
        - name: bitbucket-volume
          persistentVolumeClaim:
            claimName: bitbucket-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: bitbucket-service
  namespace: tools
spec:
  selector:
    app: bitbucket
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 7990
      protocol: TCP
      name: http